version: "3.8"

services:
  registration_service:
    build: .
    image: registration_service
    container_name: registration_service
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/registration
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=registration