version: "3.8"

services:
  registration_service:
    build: .
    image: registration_service
    container_name: registration_service
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass

  db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres