server:
  port: 8084
client:
  uri: http://localhost:8082
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
#    url: jdbc:postgresql://localhost:5432/registration
#    password: root
#    username: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
