server:
  port: 8080
client:
  uri: http://localhost:8082
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    #   url: jdbc:postgresql://51.250.41.207:5432/registration
    #  password: registration
  #  username: registration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
