server:
  port: 8084
client:
  uri: http://localhost:8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    password: pass
    username: postgres
  jpa:
    open-in-view: false
