server:
  port: 8085
user_service: ${USER_SERVICE:#{"http://51.250.41.207:8081"}}
event_service: ${EVENT_SERVICE:#{"http://51.250.41.207:8082"}}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
  #  url: jdbc:postgresql://localhost:6545/registration
  #  password: registration
  #  username: registration
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
