--liquibase formatted sql

--changeset ashvedov:1
create table if not exists registration
(
    id bigint generated by default as identity primary key,
    user_name varchar(55),
    email varchar(55),
    phone varchar(55),
    event_id bigint,
    password varchar(55)
);